name: Node.js CI

on: [push, pull_request]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: Build and Test Frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install frontend dependencies
        run: |
          cd HealthQuest/frontend
          npm install
      - name: Build frontend
        run: |
          cd HealthQuest/frontend
          npm run build
      - name: Test frontend
        run: |
          cd HealthQuest/frontend
          npm test

  build-backend:
    runs-on: ubuntu-latest
    name: Build and Test Backend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install backend dependencies
        run: |
          cd HealthQuest/backend
          npm install
      - name: Run backend tests
        run: |
          cd HealthQuest/backend
          npm test
